import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "@/Components/Provider";
import Menu from "@/Components/MenuBar/Menu";
import { AuthProvider } from "../../authContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "navigation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
